# Generated by Django 5.0.4 on 2024-11-18 22:00

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='default/user.jpg', upload_to=dashboard.models.user_directory_path),
        ),
    ]
