# Generated by Django 5.0.4 on 2024-11-23 23:43

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_crewmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(default='default/movie.jpg', upload_to=dashboard.models.movie_directory_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.crewmember')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.movie')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.role')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='crew_members',
            field=models.ManyToManyField(related_name='movies', through='dashboard.MovieCrewMember', to='dashboard.crewmember'),
        ),
    ]
