# Generated by Django 5.0.4 on 2024-11-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_status_post_posttemplate_posttemplatetemplatefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.movie'),
        ),
    ]
