# Generated by Django 5.0.4 on 2024-11-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_post_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='edited_at',
        ),
    ]
