# Generated by Django 5.0.4 on 2024-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_updated_at_post_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
